-- 2026-09-22-02-assign-per-exercise-metrics.sql
--
-- Gives every RepDB-imported exercise its own reviewed tracking mode and metrics, instead of the
-- category-level guess. Source of truth: backend/src/exercises/lib/exercise-metric-profiles.ts (the
-- importer reads the same table; exercise-metric-profiles.spec.ts keeps this file in sync with it).
--
-- Why it matters beyond the wrong fields shown in the challenge builder: the importer never wrote
-- exercise_metrics rows for RepDB exercises, and MetricsService rejects every logged metric an exercise
-- has no exercise_metrics row for — so logging reps / time / distance against these exercises was
-- failing silently (best-effort writes, errors swallowed). This gives each one the rows it needs.
--
-- Scope / safety:
--   * Only source = 'repdb' exercises, matched by source_id (the RepDB slug).
--   * tracking_mode is left alone for content_locked rows, exactly like the importer.
--   * exercise_metrics for those exercises are REPLACED by the reviewed set (RepDB exercises had none).
--   * Idempotent: re-running converges to the same state. An id that does not exist in this database
--     simply matches nothing.

-- 0. The two metric types the rest of this file relies on. The live catalog already has 'time'
-- (seconds) and 'distance' (km) — the codes the whole app uses — so there this does nothing; a database
-- rebuilt from the repo's older seed only has 'duration'/'distanceKm', which nothing reads.
INSERT INTO havit.metric_types (code, name, value_type, default_unit, description) VALUES
  ('time', 'Duration', 'seconds', NULL, 'Duration of the exercise or set'),
  ('distance', 'Distance', 'decimal', 'km', 'Distance covered during the exercise')
ON CONFLICT (code) DO NOTHING;

CREATE TEMP TABLE tmp_metric_profile (
  profile       TEXT    NOT NULL,
  tracking_mode TEXT    NOT NULL,
  metric_code   TEXT    NOT NULL,
  is_required   BOOLEAN NOT NULL,
  is_primary    BOOLEAN NOT NULL
) ON COMMIT DROP;

INSERT INTO tmp_metric_profile (profile, tracking_mode, metric_code, is_required, is_primary) VALUES
  ('weighted_reps', 'sets', 'reps', true, true),
  ('weighted_reps', 'sets', 'weight', false, false),
  ('bodyweight_reps', 'sets', 'reps', true, true),
  ('duration', 'single', 'time', true, true),
  ('loaded_duration', 'single', 'time', true, true),
  ('loaded_duration', 'single', 'weight', false, false),
  ('distance_duration', 'single', 'time', true, true),
  ('distance_duration', 'single', 'distance', false, false);

CREATE TEMP TABLE tmp_exercise_profile (
  slug    TEXT PRIMARY KEY,
  profile TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO tmp_exercise_profile (slug, profile) VALUES
  ('battle-rope-double-slam', 'bodyweight_reps'),
  ('burpees', 'bodyweight_reps'),
  ('battle-ropes', 'duration'),
  ('high-knees', 'duration'),
  ('jump-rope', 'duration'),
  ('jumping-jacks', 'duration'),
  ('mountain-climbers', 'duration'),
  ('stair-climber', 'duration'),
  ('air-bike', 'distance_duration'),
  ('elliptical-trainer', 'distance_duration'),
  ('incline-treadmill-walk', 'distance_duration'),
  ('rowing-machine', 'distance_duration'),
  ('running', 'distance_duration'),
  ('stationary-bike', 'distance_duration'),
  ('treadmill-running', 'distance_duration'),
  ('walking', 'distance_duration'),
  ('box-jump', 'bodyweight_reps'),
  ('jump-squat', 'bodyweight_reps'),
  ('plyo-lunge', 'bodyweight_reps'),
  ('plyo-push-up', 'bodyweight_reps'),
  ('clean', 'weighted_reps'),
  ('clean-and-jerk', 'weighted_reps'),
  ('double-kettlebell-dead-clean', 'weighted_reps'),
  ('double-kettlebell-dead-split-snatch', 'weighted_reps'),
  ('double-kettlebell-split-jerk', 'weighted_reps'),
  ('double-kettlebell-swing-snatch', 'weighted_reps'),
  ('dumbbell-snatch', 'weighted_reps'),
  ('hang-clean', 'weighted_reps'),
  ('hang-power-clean', 'weighted_reps'),
  ('kettlebell-swing-clean', 'weighted_reps'),
  ('muscle-snatch', 'weighted_reps'),
  ('push-jerk', 'weighted_reps'),
  ('snatch', 'weighted_reps'),
  ('split-jerk', 'weighted_reps'),
  ('cat-cow', 'bodyweight_reps'),
  ('downward-dog-pedal', 'bodyweight_reps'),
  ('downward-dog-to-low-lunge', 'bodyweight_reps'),
  ('half-kneeling-hip-flexor-rock', 'bodyweight_reps'),
  ('low-lunge-to-half-split', 'bodyweight_reps'),
  ('pilates-roll-down', 'bodyweight_reps'),
  ('pilates-saw', 'bodyweight_reps'),
  ('pilates-spine-stretch-forward', 'bodyweight_reps'),
  ('pilates-spine-twist', 'bodyweight_reps'),
  ('standing-forward-fold-to-half-lift', 'bodyweight_reps'),
  ('standing-side-bend-flow', 'bodyweight_reps'),
  ('thread-the-needle-flow', 'bodyweight_reps'),
  ('banded-adductor-stretch', 'duration'),
  ('banded-ankle-stretch', 'duration'),
  ('banded-calf-stretch', 'duration'),
  ('banded-chest-stretch', 'duration'),
  ('banded-figure-4-stretch', 'duration'),
  ('banded-hamstring-stretch', 'duration'),
  ('banded-it-band-stretch', 'duration'),
  ('banded-lat-stretch', 'duration'),
  ('banded-rear-delt-stretch', 'duration'),
  ('banded-shoulder-stretch', 'duration'),
  ('banded-triceps-stretch', 'duration'),
  ('bench-adductor-stretch', 'duration'),
  ('bench-ankle-stretch', 'duration'),
  ('bench-bulgarian-split-stretch', 'duration'),
  ('bench-calf-stretch', 'duration'),
  ('bench-chest-stretch', 'duration'),
  ('bench-childs-pose', 'duration'),
  ('bench-couch-stretch', 'duration'),
  ('bench-figure-4-glute-stretch', 'duration'),
  ('bench-hamstring-stretch', 'duration'),
  ('bench-lat-stretch', 'duration'),
  ('butterfly-stretch', 'duration'),
  ('camel-pose', 'duration'),
  ('cat-stretch', 'duration'),
  ('childs-pose', 'duration'),
  ('cobra-stretch', 'duration'),
  ('cow-face-pose', 'duration'),
  ('cross-body-shoulder-stretch', 'duration'),
  ('doorway-chest-stretch', 'duration'),
  ('downward-dog', 'duration'),
  ('easy-pose', 'duration'),
  ('fish-pose', 'duration'),
  ('garland-pose', 'duration'),
  ('happy-baby', 'duration'),
  ('head-to-knee-pose', 'duration'),
  ('hero-pose', 'duration'),
  ('knee-to-chest-stretch', 'duration'),
  ('kneeling-hip-flexor-stretch', 'duration'),
  ('kneeling-wrist-stretch', 'duration'),
  ('legs-up-the-wall', 'duration'),
  ('lizard-stretch', 'duration'),
  ('low-lunge', 'duration'),
  ('mountain-pose', 'duration'),
  ('neck-side-stretch', 'duration'),
  ('overhead-triceps-stretch', 'duration'),
  ('pigeon-stretch', 'duration'),
  ('plow-pose', 'duration'),
  ('puppy-pose', 'duration'),
  ('pyramid-pose', 'duration'),
  ('savasana', 'duration'),
  ('seated-forward-fold', 'duration'),
  ('seated-spinal-twist', 'duration'),
  ('seated-straddle-stretch', 'duration'),
  ('sphinx-pose', 'duration'),
  ('standing-calf-stretch', 'duration'),
  ('standing-forward-fold', 'duration'),
  ('standing-quad-stretch', 'duration'),
  ('standing-side-bend', 'duration'),
  ('standing-split', 'duration'),
  ('supine-spinal-twist', 'duration'),
  ('thread-the-needle', 'duration'),
  ('triangle-pose', 'duration'),
  ('upward-dog', 'duration'),
  ('wide-legged-forward-fold', 'duration'),
  ('arnold-press', 'weighted_reps'),
  ('assisted-dips', 'weighted_reps'),
  ('assisted-pull-ups', 'weighted_reps'),
  ('barbell-calf-raise', 'weighted_reps'),
  ('barbell-curl', 'weighted_reps'),
  ('barbell-front-raise', 'weighted_reps'),
  ('barbell-glute-bridge', 'weighted_reps'),
  ('barbell-lunge', 'weighted_reps'),
  ('barbell-overhead-extension', 'weighted_reps'),
  ('barbell-preacher-curl', 'weighted_reps'),
  ('barbell-pullover', 'weighted_reps'),
  ('barbell-rear-delt-row', 'weighted_reps'),
  ('barbell-reverse-lunge', 'weighted_reps'),
  ('barbell-row', 'weighted_reps'),
  ('barbell-wrist-curl', 'weighted_reps'),
  ('behind-the-back-barbell-shrug', 'weighted_reps'),
  ('behind-the-neck-lat-pulldown', 'weighted_reps'),
  ('behind-the-neck-press', 'weighted_reps'),
  ('bench-press', 'weighted_reps'),
  ('bench-pull', 'weighted_reps'),
  ('bent-arm-barbell-pullover', 'weighted_reps'),
  ('bent-arm-ez-bar-pullover', 'weighted_reps'),
  ('bent-over-db-row', 'weighted_reps'),
  ('bent-over-ez-bar-row', 'weighted_reps'),
  ('bicep-curl', 'weighted_reps'),
  ('bulgarian-split-squat', 'weighted_reps'),
  ('cable-bent-over-row', 'weighted_reps'),
  ('cable-chest-press', 'weighted_reps'),
  ('cable-crunch', 'weighted_reps'),
  ('cable-curl', 'weighted_reps'),
  ('cable-external-rotation', 'weighted_reps'),
  ('cable-fly', 'weighted_reps'),
  ('cable-front-raise', 'weighted_reps'),
  ('cable-hammer-curl', 'weighted_reps'),
  ('cable-kickback', 'weighted_reps'),
  ('cable-lateral-raise', 'weighted_reps'),
  ('cable-pallof-press', 'weighted_reps'),
  ('cable-tricep-kickback', 'weighted_reps'),
  ('cable-upright-row', 'weighted_reps'),
  ('cable-wrist-curl', 'weighted_reps'),
  ('cheat-curl', 'weighted_reps'),
  ('chest-press-machine', 'weighted_reps'),
  ('chest-supported-db-row', 'weighted_reps'),
  ('chest-supported-dumbbell-shrug', 'weighted_reps'),
  ('chest-supported-kettlebell-row', 'weighted_reps'),
  ('chest-supported-smith-machine-row', 'weighted_reps'),
  ('close-grip-barbell-curl', 'weighted_reps'),
  ('close-grip-bench-press', 'weighted_reps'),
  ('close-grip-db-bench-press', 'weighted_reps'),
  ('close-grip-ez-bar-bench-press', 'weighted_reps'),
  ('close-grip-ez-bar-curl', 'weighted_reps'),
  ('close-grip-incline-bench', 'weighted_reps'),
  ('close-grip-lat-pulldown', 'weighted_reps'),
  ('close-stance-leg-press', 'weighted_reps'),
  ('concentration-curl', 'weighted_reps'),
  ('cross-body-hammer-curl', 'weighted_reps'),
  ('db-bench-press', 'weighted_reps'),
  ('db-fly', 'weighted_reps'),
  ('db-kickstand-deadlift', 'weighted_reps'),
  ('db-lunge', 'weighted_reps'),
  ('db-pullover', 'weighted_reps'),
  ('db-reverse-curl', 'weighted_reps'),
  ('db-reverse-wrist-curl', 'weighted_reps'),
  ('db-shrug', 'weighted_reps'),
  ('db-skull-crusher', 'weighted_reps'),
  ('db-somersault-squat', 'weighted_reps'),
  ('db-squat', 'weighted_reps'),
  ('db-sumo-squat', 'weighted_reps'),
  ('db-svend-press', 'weighted_reps'),
  ('deadlift', 'weighted_reps'),
  ('decline-bench-press', 'weighted_reps'),
  ('decline-bench-press-barbell', 'weighted_reps'),
  ('decline-bench-press-ez-bar', 'weighted_reps'),
  ('decline-db-fly', 'weighted_reps'),
  ('deficit-deadlift', 'weighted_reps'),
  ('double-db-kickstand-deadlift', 'weighted_reps'),
  ('double-kettlebell-bicep-curl', 'weighted_reps'),
  ('double-kettlebell-clean', 'weighted_reps'),
  ('double-kettlebell-clean-and-press', 'weighted_reps'),
  ('double-kettlebell-jerk', 'weighted_reps'),
  ('double-kettlebell-overhead-press', 'weighted_reps'),
  ('double-kettlebell-push-press', 'weighted_reps'),
  ('double-kettlebell-rear-delt-row', 'weighted_reps'),
  ('double-kettlebell-row', 'weighted_reps'),
  ('drag-curl', 'weighted_reps'),
  ('dumbbell-bench-pull', 'weighted_reps'),
  ('dumbbell-calf-raise', 'weighted_reps'),
  ('dumbbell-deadlift', 'weighted_reps'),
  ('dumbbell-face-pull', 'weighted_reps'),
  ('dumbbell-floor-press', 'weighted_reps'),
  ('dumbbell-front-raise', 'weighted_reps'),
  ('dumbbell-front-squat', 'weighted_reps'),
  ('dumbbell-hip-thrust', 'weighted_reps'),
  ('dumbbell-pistol-squat', 'weighted_reps'),
  ('dumbbell-push-press', 'weighted_reps'),
  ('dumbbell-reverse-fly', 'weighted_reps'),
  ('dumbbell-romanian-deadlift', 'weighted_reps'),
  ('dumbbell-shoulder-press', 'weighted_reps'),
  ('dumbbell-side-bend', 'weighted_reps'),
  ('dumbbell-split-squat', 'weighted_reps'),
  ('dumbbell-tricep-extension', 'weighted_reps'),
  ('dumbbell-upright-row', 'weighted_reps'),
  ('dumbbell-windmill', 'weighted_reps'),
  ('dumbbell-wrist-curl', 'weighted_reps'),
  ('ez-bar-bench-press', 'weighted_reps'),
  ('ez-bar-curl', 'weighted_reps'),
  ('ez-bar-front-raise', 'weighted_reps'),
  ('ez-bar-lying-tricep-extension', 'weighted_reps'),
  ('ez-bar-overhead-extension', 'weighted_reps'),
  ('ez-bar-pullover', 'weighted_reps'),
  ('ez-bar-reverse-curl', 'weighted_reps'),
  ('ez-bar-reverse-grip-row', 'weighted_reps'),
  ('ez-bar-romanian-deadlift', 'weighted_reps'),
  ('ez-bar-shrug', 'weighted_reps'),
  ('ez-bar-spider-curl', 'weighted_reps'),
  ('ez-bar-upright-row', 'weighted_reps'),
  ('ez-bar-wrist-curl', 'weighted_reps'),
  ('face-pull', 'weighted_reps'),
  ('floor-ez-bar-press', 'weighted_reps'),
  ('floor-kettlebell-pullover', 'weighted_reps'),
  ('floor-press', 'weighted_reps'),
  ('front-squat', 'weighted_reps'),
  ('goblet-squat', 'weighted_reps'),
  ('good-morning', 'weighted_reps'),
  ('hack-squat', 'weighted_reps'),
  ('hack-squat-calf-raise', 'weighted_reps'),
  ('hammer-curl', 'weighted_reps'),
  ('heel-elevated-squat', 'weighted_reps'),
  ('hex-bar-deadlift', 'weighted_reps'),
  ('high-foot-leg-press', 'weighted_reps'),
  ('hip-abduction', 'weighted_reps'),
  ('hip-adduction', 'weighted_reps'),
  ('hip-thrust', 'weighted_reps'),
  ('horizontal-leg-press', 'weighted_reps'),
  ('incline-bench-ez-bar-press', 'weighted_reps'),
  ('incline-bench-press', 'weighted_reps'),
  ('incline-db-curl', 'weighted_reps'),
  ('incline-db-press', 'weighted_reps'),
  ('incline-dumbbell-fly', 'weighted_reps'),
  ('incline-hammer-curl', 'weighted_reps'),
  ('jefferson-curl', 'weighted_reps'),
  ('kettlebell-bulgarian-split-squat', 'weighted_reps'),
  ('kettlebell-close-grip-floor-press', 'weighted_reps'),
  ('kettlebell-concentration-curl', 'weighted_reps'),
  ('kettlebell-deadlift', 'weighted_reps'),
  ('kettlebell-floor-press', 'weighted_reps'),
  ('kettlebell-goblet-lunge', 'weighted_reps'),
  ('kettlebell-halo', 'weighted_reps'),
  ('kettlebell-hammer-curl', 'weighted_reps'),
  ('kettlebell-hip-thrust', 'weighted_reps'),
  ('kettlebell-kickstand-deadlift', 'weighted_reps'),
  ('kettlebell-lunge-press', 'weighted_reps'),
  ('kettlebell-offset-reverse-lunge-and-press', 'weighted_reps'),
  ('kettlebell-overhead-tricep-extension', 'weighted_reps'),
  ('kettlebell-pistol-squat', 'weighted_reps'),
  ('kettlebell-pullover', 'weighted_reps'),
  ('kettlebell-reverse-lunge', 'weighted_reps'),
  ('kettlebell-reverse-wrist-curl', 'weighted_reps'),
  ('kettlebell-rotational-lunge', 'weighted_reps'),
  ('kettlebell-russian-twist', 'weighted_reps'),
  ('kettlebell-shrug', 'weighted_reps'),
  ('kettlebell-single-leg-deadlift', 'weighted_reps'),
  ('kettlebell-skull-crusher', 'weighted_reps'),
  ('kettlebell-squat', 'weighted_reps'),
  ('kettlebell-sumo-deadlift', 'weighted_reps'),
  ('kettlebell-sumo-high-pull', 'weighted_reps'),
  ('kettlebell-svend-press', 'weighted_reps'),
  ('kettlebell-swing', 'weighted_reps'),
  ('kettlebell-turkish-get-ups', 'weighted_reps'),
  ('kettlebell-windmills', 'weighted_reps'),
  ('kettlebell-wrist-curl', 'weighted_reps'),
  ('kneeling-cable-row', 'weighted_reps'),
  ('landmine-press', 'weighted_reps'),
  ('lat-pulldown', 'weighted_reps'),
  ('lateral-raise', 'weighted_reps'),
  ('leg-curl', 'weighted_reps'),
  ('leg-extension', 'weighted_reps'),
  ('leg-press', 'weighted_reps'),
  ('lying-tricep-extension', 'weighted_reps'),
  ('machine-back-extension', 'weighted_reps'),
  ('machine-bicep-curl', 'weighted_reps'),
  ('machine-calf-raise', 'weighted_reps'),
  ('machine-chest-fly', 'weighted_reps'),
  ('machine-preacher-curl', 'weighted_reps'),
  ('machine-seated-crunch', 'weighted_reps'),
  ('machine-shoulder-press', 'weighted_reps'),
  ('machine-triceps-extension', 'weighted_reps'),
  ('medicine-ball-slam', 'weighted_reps'),
  ('ohp', 'weighted_reps'),
  ('one-arm-dumbbell-push-press', 'weighted_reps'),
  ('one-arm-dumbbell-swing', 'weighted_reps'),
  ('one-arm-kettlebell-bicep-curl', 'weighted_reps'),
  ('one-arm-kettlebell-bottoms-up-press', 'weighted_reps'),
  ('one-arm-kettlebell-floor-glute-bridge-press', 'weighted_reps'),
  ('one-arm-kettlebell-floor-press', 'weighted_reps'),
  ('one-arm-kettlebell-front-squat', 'weighted_reps'),
  ('one-arm-kettlebell-push-press', 'weighted_reps'),
  ('one-arm-kettlebell-row', 'weighted_reps'),
  ('one-arm-kettlebell-shoulder-press', 'weighted_reps'),
  ('one-arm-kettlebell-swing', 'weighted_reps'),
  ('one-arm-kettlebell-tricep-kickback', 'weighted_reps'),
  ('one-arm-landmine-press', 'weighted_reps'),
  ('one-arm-lat-pulldown', 'weighted_reps'),
  ('one-arm-single-leg-dumbbell-romanian-deadlift', 'weighted_reps'),
  ('one-arm-single-leg-kettlebell-romanian-deadlift', 'weighted_reps'),
  ('overhead-squat', 'weighted_reps'),
  ('overhead-tricep-extension', 'weighted_reps'),
  ('pause-deadlift', 'weighted_reps'),
  ('pause-squat', 'weighted_reps'),
  ('paused-bench-press', 'weighted_reps'),
  ('paused-incline-bench-press', 'weighted_reps'),
  ('paused-ohp', 'weighted_reps'),
  ('pec-deck', 'weighted_reps'),
  ('pendlay-row', 'weighted_reps'),
  ('plate-loaded-donkey-calf-raise', 'weighted_reps'),
  ('plate-loaded-glute-drive', 'weighted_reps'),
  ('plate-loaded-lateral-raise', 'weighted_reps'),
  ('plate-loaded-shrug', 'weighted_reps'),
  ('plate-pullover', 'weighted_reps'),
  ('preacher-curl', 'weighted_reps'),
  ('preacher-hammer-curl', 'weighted_reps'),
  ('push-press', 'weighted_reps'),
  ('rack-pull', 'weighted_reps'),
  ('rear-delt-fly', 'weighted_reps'),
  ('reverse-curl', 'weighted_reps'),
  ('reverse-grip-bent-over-row', 'weighted_reps'),
  ('reverse-grip-lat-pulldown', 'weighted_reps'),
  ('reverse-lunge', 'weighted_reps'),
  ('romanian-deadlift', 'weighted_reps'),
  ('seated-barbell-overhead-press', 'weighted_reps'),
  ('seated-cable-row', 'weighted_reps'),
  ('seated-calf-raise', 'weighted_reps'),
  ('seated-db-press', 'weighted_reps'),
  ('seated-dumbbell-curl', 'weighted_reps'),
  ('seated-dumbbell-lateral-raise', 'weighted_reps'),
  ('seated-dumbbell-tricep-extension', 'weighted_reps'),
  ('seated-leg-curl', 'weighted_reps'),
  ('seated-smith-machine-shoulder-press', 'weighted_reps'),
  ('shrug', 'weighted_reps'),
  ('side-lying-lateral-raise', 'weighted_reps'),
  ('single-arm-chest-supported-dumbbell-row', 'weighted_reps'),
  ('single-arm-db-row', 'weighted_reps'),
  ('single-arm-dumbbell-overhead-tricep-extension', 'weighted_reps'),
  ('single-arm-hammer-curl', 'weighted_reps'),
  ('single-arm-machine-shoulder-press', 'weighted_reps'),
  ('single-arm-plate-loaded-lateral-raise', 'weighted_reps'),
  ('single-arm-tricep-pushdown', 'weighted_reps'),
  ('single-db-svend-press', 'weighted_reps'),
  ('single-leg-extension', 'weighted_reps'),
  ('single-leg-lying-leg-curl', 'weighted_reps'),
  ('single-leg-press', 'weighted_reps'),
  ('single-leg-romanian-deadlift', 'weighted_reps'),
  ('skull-crusher', 'weighted_reps'),
  ('smith-machine-bench-press', 'weighted_reps'),
  ('smith-machine-bent-over-row', 'weighted_reps'),
  ('smith-machine-bulgarian-split', 'weighted_reps'),
  ('smith-machine-calf-raise', 'weighted_reps'),
  ('smith-machine-decline-bench-press', 'weighted_reps'),
  ('smith-machine-front-squat', 'weighted_reps'),
  ('smith-machine-good-morning', 'weighted_reps'),
  ('smith-machine-hip-thrust', 'weighted_reps'),
  ('smith-machine-incline-bench-press', 'weighted_reps'),
  ('smith-machine-rdl', 'weighted_reps'),
  ('smith-machine-reverse-grip-bent-over-row', 'weighted_reps'),
  ('smith-machine-reverse-lunge', 'weighted_reps'),
  ('smith-machine-shoulder-press', 'weighted_reps'),
  ('smith-machine-shrug', 'weighted_reps'),
  ('smith-machine-split-squat', 'weighted_reps'),
  ('smith-machine-squat', 'weighted_reps'),
  ('smith-machine-upright-row', 'weighted_reps'),
  ('spider-curl', 'weighted_reps'),
  ('spoto-press', 'weighted_reps'),
  ('squat', 'weighted_reps'),
  ('standing-calf-raise', 'weighted_reps'),
  ('stiff-leg-deadlift', 'weighted_reps'),
  ('straight-arm-pulldown', 'weighted_reps'),
  ('straight-bar-cable-front-raise', 'weighted_reps'),
  ('strict-curl', 'weighted_reps'),
  ('sumo-deadlift', 'weighted_reps'),
  ('sumo-squat', 'weighted_reps'),
  ('svend-press', 'weighted_reps'),
  ('t-bar-row', 'weighted_reps'),
  ('thruster', 'weighted_reps'),
  ('tricep-kickback', 'weighted_reps'),
  ('tricep-pushdown', 'weighted_reps'),
  ('upright-row', 'weighted_reps'),
  ('v-bar-lat-pulldown', 'weighted_reps'),
  ('v-bar-tricep-pushdown', 'weighted_reps'),
  ('weighted-dips', 'weighted_reps'),
  ('weighted-pull-up', 'weighted_reps'),
  ('weighted-wall-crunch', 'weighted_reps'),
  ('wide-grip-bench-press', 'weighted_reps'),
  ('wide-grip-seated-cable-row', 'weighted_reps'),
  ('wide-stance-leg-press', 'weighted_reps'),
  ('wrist-curl', 'weighted_reps'),
  ('wrist-roller', 'weighted_reps'),
  ('zottman-curl', 'weighted_reps'),
  ('ab-wheel-rollout', 'bodyweight_reps'),
  ('archer-pull-ups', 'bodyweight_reps'),
  ('archer-push-ups', 'bodyweight_reps'),
  ('back-extension', 'bodyweight_reps'),
  ('ball-leg-curl', 'bodyweight_reps'),
  ('ball-pike', 'bodyweight_reps'),
  ('band-assisted-pull-ups', 'bodyweight_reps'),
  ('band-pull-apart', 'bodyweight_reps'),
  ('banded-clamshell', 'bodyweight_reps'),
  ('banded-fire-hydrant', 'bodyweight_reps'),
  ('banded-glute-bridge', 'bodyweight_reps'),
  ('banded-good-morning', 'bodyweight_reps'),
  ('banded-hip-thrust', 'bodyweight_reps'),
  ('banded-kneeling-hip-thrust', 'bodyweight_reps'),
  ('banded-lateral-walk', 'bodyweight_reps'),
  ('banded-romanian-deadlift', 'bodyweight_reps'),
  ('banded-seated-hip-abduction', 'bodyweight_reps'),
  ('banded-squat', 'bodyweight_reps'),
  ('banded-standing-curl', 'bodyweight_reps'),
  ('banded-standing-hip-abduction', 'bodyweight_reps'),
  ('banded-standing-hip-adduction', 'bodyweight_reps'),
  ('banded-sumo-walk', 'bodyweight_reps'),
  ('banded-terminal-knee-extension', 'bodyweight_reps'),
  ('barbell-ab-rollout', 'bodyweight_reps'),
  ('behind-the-neck-pull-ups', 'bodyweight_reps'),
  ('bench-dips', 'bodyweight_reps'),
  ('bench-leg-pull-in', 'bodyweight_reps'),
  ('bicycle-crunch', 'bodyweight_reps'),
  ('bird-dog', 'bodyweight_reps'),
  ('bodyweight-calf-raise', 'bodyweight_reps'),
  ('bodyweight-good-morning', 'bodyweight_reps'),
  ('bodyweight-lateral-raise', 'bodyweight_reps'),
  ('bodyweight-overhead-press', 'bodyweight_reps'),
  ('bodyweight-reverse-lunge', 'bodyweight_reps'),
  ('bodyweight-squat', 'bodyweight_reps'),
  ('box-squat', 'bodyweight_reps'),
  ('captains-chair-knee-raise', 'bodyweight_reps'),
  ('captains-chair-leg-raise', 'bodyweight_reps'),
  ('chin-ups', 'bodyweight_reps'),
  ('clamshells', 'bodyweight_reps'),
  ('clap-push-ups', 'bodyweight_reps'),
  ('close-grip-pull-ups', 'bodyweight_reps'),
  ('close-grip-push-ups', 'bodyweight_reps'),
  ('cocoons', 'bodyweight_reps'),
  ('cossack-squat', 'bodyweight_reps'),
  ('crab-dips', 'bodyweight_reps'),
  ('cross-body-crunch', 'bodyweight_reps'),
  ('crunches', 'bodyweight_reps'),
  ('dead-bug', 'bodyweight_reps'),
  ('decline-crunch', 'bodyweight_reps'),
  ('decline-push-up', 'bodyweight_reps'),
  ('deficit-push-ups', 'bodyweight_reps'),
  ('diamond-push-ups', 'bodyweight_reps'),
  ('dips', 'bodyweight_reps'),
  ('donkey-calf-raise', 'bodyweight_reps'),
  ('downward-dog-knee-tuck', 'bodyweight_reps'),
  ('downward-dog-to-knee-drive', 'bodyweight_reps'),
  ('downward-dog-to-plank', 'bodyweight_reps'),
  ('downward-dog-to-upward-dog', 'bodyweight_reps'),
  ('dragon-flag', 'bodyweight_reps'),
  ('glute-bridge', 'bodyweight_reps'),
  ('glute-kickback', 'bodyweight_reps'),
  ('handstand-push-ups', 'bodyweight_reps'),
  ('hanging-knee-raise', 'bodyweight_reps'),
  ('hanging-leg-raise', 'bodyweight_reps'),
  ('hanging-pike', 'bodyweight_reps'),
  ('heel-to-toe-walk', 'bodyweight_reps'),
  ('incline-push-ups', 'bodyweight_reps'),
  ('inverted-row', 'bodyweight_reps'),
  ('jackknife-sit-up', 'bodyweight_reps'),
  ('knee-push-ups', 'bodyweight_reps'),
  ('lunge', 'bodyweight_reps'),
  ('lying-leg-raise', 'bodyweight_reps'),
  ('muscle-ups', 'bodyweight_reps'),
  ('negative-pull-ups', 'bodyweight_reps'),
  ('neutral-grip-pull-ups', 'bodyweight_reps'),
  ('nordic-hamstring-curl', 'bodyweight_reps'),
  ('pause-pull-up', 'bodyweight_reps'),
  ('pike-push-ups', 'bodyweight_reps'),
  ('pilates-kneeling-side-kick', 'bodyweight_reps'),
  ('pilates-leg-pull-back', 'bodyweight_reps'),
  ('pilates-leg-pull-front', 'bodyweight_reps'),
  ('pilates-roll-over', 'bodyweight_reps'),
  ('pilates-side-bend', 'bodyweight_reps'),
  ('pistol-squat', 'bodyweight_reps'),
  ('pseudo-planche-push-ups', 'bodyweight_reps'),
  ('pull-up', 'bodyweight_reps'),
  ('push-up', 'bodyweight_reps'),
  ('reverse-crunches', 'bodyweight_reps'),
  ('reverse-nordic-curl', 'bodyweight_reps'),
  ('reverse-plank-dips', 'bodyweight_reps'),
  ('reverse-tabletop-hip-pulses', 'bodyweight_reps'),
  ('ring-dips', 'bodyweight_reps'),
  ('ring-face-pull', 'bodyweight_reps'),
  ('ring-muscle-up', 'bodyweight_reps'),
  ('ring-push-up', 'bodyweight_reps'),
  ('ring-row', 'bodyweight_reps'),
  ('rings-inverted-row', 'bodyweight_reps'),
  ('rope-climb', 'bodyweight_reps'),
  ('russian-twist', 'bodyweight_reps'),
  ('scapular-pull-ups', 'bodyweight_reps'),
  ('side-lunge', 'bodyweight_reps'),
  ('side-lying-hip-abduction', 'bodyweight_reps'),
  ('side-lying-hip-adduction', 'bodyweight_reps'),
  ('side-plank-leg-lift', 'bodyweight_reps'),
  ('single-leg-calf-raise', 'bodyweight_reps'),
  ('single-leg-glute-bridge', 'bodyweight_reps'),
  ('sit-ups', 'bodyweight_reps'),
  ('split-squat', 'bodyweight_reps'),
  ('stability-ball-hip-bridge', 'bodyweight_reps'),
  ('stability-ball-knee-tuck', 'bodyweight_reps'),
  ('stability-ball-push-up', 'bodyweight_reps'),
  ('stability-ball-push-up-hands-on-ball', 'bodyweight_reps'),
  ('stability-ball-wall-squat', 'bodyweight_reps'),
  ('step-ups', 'bodyweight_reps'),
  ('straight-bar-dips', 'bodyweight_reps'),
  ('superman', 'bodyweight_reps'),
  ('supine-windshield-wipers', 'bodyweight_reps'),
  ('toes-to-bar', 'bodyweight_reps'),
  ('trx-bicep-curl', 'bodyweight_reps'),
  ('trx-chest-press', 'bodyweight_reps'),
  ('trx-face-pull', 'bodyweight_reps'),
  ('trx-hamstring-curl', 'bodyweight_reps'),
  ('trx-lunge', 'bodyweight_reps'),
  ('trx-pistol-squat', 'bodyweight_reps'),
  ('trx-row', 'bodyweight_reps'),
  ('trx-squat', 'bodyweight_reps'),
  ('trx-tricep-extension', 'bodyweight_reps'),
  ('trx-y-fly', 'bodyweight_reps'),
  ('v-ups', 'bodyweight_reps'),
  ('walking-lunge', 'bodyweight_reps'),
  ('wall-push-ups', 'bodyweight_reps'),
  ('wide-grip-pull-ups', 'bodyweight_reps'),
  ('wide-grip-push-ups', 'bodyweight_reps'),
  ('back-lever', 'duration'),
  ('bear-crawl', 'duration'),
  ('bird-dog-hold', 'duration'),
  ('boat-pose', 'duration'),
  ('bow-pose', 'duration'),
  ('chair-pose', 'duration'),
  ('chin-tuck-hold', 'duration'),
  ('clamshells-hold', 'duration'),
  ('crescent-lunge', 'duration'),
  ('crow-pose', 'duration'),
  ('dancer-pose', 'duration'),
  ('dead-bug-hold', 'duration'),
  ('dead-hang', 'duration'),
  ('dolphin-pose', 'duration'),
  ('eagle-pose', 'duration'),
  ('extended-side-angle', 'duration'),
  ('flutter-kicks', 'duration'),
  ('front-lever', 'duration'),
  ('glute-bridge-hold', 'duration'),
  ('glute-kickback-hold', 'duration'),
  ('half-moon-pose', 'duration'),
  ('high-plank', 'duration'),
  ('hollow-body-hold', 'duration'),
  ('human-flag', 'duration'),
  ('isometric-neck-side', 'duration'),
  ('l-sit', 'duration'),
  ('locust-pose', 'duration'),
  ('planche', 'duration'),
  ('plank', 'duration'),
  ('reverse-plank', 'duration'),
  ('reverse-tabletop-hold', 'duration'),
  ('revolved-chair-pose', 'duration'),
  ('revolved-crescent-lunge', 'duration'),
  ('ring-dead-hang', 'duration'),
  ('scissor-kicks', 'duration'),
  ('side-lying-hip-abduction-hold', 'duration'),
  ('side-lying-hip-adduction-hold', 'duration'),
  ('side-plank', 'duration'),
  ('side-plank-leg-lift-hold', 'duration'),
  ('single-leg-glute-bridge-hold', 'duration'),
  ('supported-shoulderstand', 'duration'),
  ('thoracic-bridge', 'duration'),
  ('three-legged-dog', 'duration'),
  ('tree-pose', 'duration'),
  ('trx-plank', 'duration'),
  ('trx-side-plank', 'duration'),
  ('v-sit', 'duration'),
  ('wall-sit', 'duration'),
  ('warrior-one', 'duration'),
  ('warrior-three', 'duration'),
  ('warrior-two', 'duration'),
  ('db-overhead-carry', 'loaded_duration'),
  ('double-db-overhead-carry', 'loaded_duration'),
  ('double-kettlebell-overhead-carry', 'loaded_duration'),
  ('dumbbell-farmers-walk', 'loaded_duration'),
  ('kettlebell-farmers-walk', 'loaded_duration'),
  ('kettlebell-overhead-carry', 'loaded_duration'),
  ('plate-pinch', 'loaded_duration'),
  ('sled-row', 'loaded_duration'),
  ('suitcase-carry', 'loaded_duration');

-- 1. Tracking mode: 'sets' (sets x reps editor) vs 'single' (one value per metric).
UPDATE havit.exercises AS e
SET tracking_mode = p.tracking_mode::havit.tracking_mode_enum
FROM (
  SELECT DISTINCT ep.slug, mp.tracking_mode
  FROM tmp_exercise_profile ep
  JOIN tmp_metric_profile mp ON mp.profile = ep.profile
) AS p
WHERE e.source = 'repdb'
  AND e.source_id = p.slug
  AND e.content_locked = false
  AND e.tracking_mode IS DISTINCT FROM p.tracking_mode::havit.tracking_mode_enum;

-- 2. Metrics: replace whatever was there with the reviewed set.
DELETE FROM havit.exercise_metrics AS em
USING havit.exercises AS e, tmp_exercise_profile AS ep
WHERE em.exercise_id = e.id
  AND e.source = 'repdb'
  AND e.source_id = ep.slug;

INSERT INTO havit.exercise_metrics (exercise_id, metric_type_id, is_required, is_primary, default_unit)
SELECT e.id, mt.id, mp.is_required, mp.is_primary, mt.default_unit
FROM tmp_exercise_profile ep
JOIN tmp_metric_profile mp ON mp.profile = ep.profile
JOIN havit.exercises e ON e.source = 'repdb' AND e.source_id = ep.slug
JOIN havit.metric_types mt ON mt.code = mp.metric_code
ON CONFLICT (exercise_id, metric_type_id) DO UPDATE
  SET is_required = EXCLUDED.is_required,
      is_primary  = EXCLUDED.is_primary,
      default_unit = EXCLUDED.default_unit;
